package SmartFarm.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Crate_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
    tgs.append("Crate id i.e CRowColumn: ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.id$_eJJ));
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.crop$_7ff));
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.sensor$_7Hh));
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$_eJJ = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6acdL, 0x4868eb0de627f4efL, "id");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink crop$_7ff = MetaAdapterFactory.getContainmentLink(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6acdL, 0x4868eb0de627f4e4L, "crop");
    /*package*/ static final SContainmentLink sensor$_7Hh = MetaAdapterFactory.getContainmentLink(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6acdL, 0x4868eb0de627f4e6L, "sensor");
  }
}
