package SmartFarm.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Temperature_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("Temperature in degree celcius");
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.DegreeCelcius$1Sbc)) {
      tgs.append("true");
      tgs.newLine();

    }
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.airtemp$1ZdE)) {
      tgs.append("Air Temperature Sensor");
      tgs.newLine();

    }

    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.plantstemp$1YhA)) {
      tgs.append("Plant Temperature Sensor");
      tgs.newLine();

    }
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.soiltemp$1SDe)) {
      tgs.append("Soil Temperature Sensor");
      tgs.newLine();

    }



  }

  private static final class PROPS {
    /*package*/ static final SProperty DegreeCelcius$1Sbc = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904bdfL, 0x4ba697e93490cfc5L, "DegreeCelcius");
    /*package*/ static final SProperty airtemp$1ZdE = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904bdfL, 0x4ba697e93490cfceL, "airtemp");
    /*package*/ static final SProperty plantstemp$1YhA = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904bdfL, 0x4ba697e93490cfcaL, "plantstemp");
    /*package*/ static final SProperty soiltemp$1SDe = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904bdfL, 0x4ba697e93490cfc7L, "soiltemp");
  }
}
