package SmartFarm.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Farm_Constraints extends BaseConstraintsDescriptor {
  public Farm_Constraints() {
    super(CONCEPTS.Farm$Gk);
  }

  public static class Cratesrequired_Property extends BasePropertyConstraintsDescriptor {
    public Cratesrequired_Property(ConstraintsDescriptor container) {
      super(PROPS.cratesrequired$tyWJ, container, true, true, false);
    }
    @Override
    public Object getValue(SNode node) {
      return SPropertyOperations.getInteger(node, PROPS.cratesrequired$tyWJ);
    }
    @Override
    public void setPropertyValue(SNode node, Object propertyValue) {
      staticSetPropertyValue(node, SPropertyOperations.castInteger(propertyValue));
    }
    private static void staticSetPropertyValue(SNode node, int propertyValue) {
      SPropertyOperations.assign(node, PROPS.cratesrequired$tyWJ, SPropertyOperations.getInteger(node, PROPS.nocol$VChW) * SPropertyOperations.getInteger(node, PROPS.norow$VB$T));
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.cratesrequired$tyWJ, new Cratesrequired_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Farm$Gk = MetaAdapterFactory.getConcept(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, "SmartFarm.structure.Farm");
  }

  private static final class PROPS {
    /*package*/ static final SProperty cratesrequired$tyWJ = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61ead32L, "cratesrequired");
    /*package*/ static final SProperty norow$VB$T = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61edcfaL, "norow");
    /*package*/ static final SProperty nocol$VChW = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61edcfdL, "nocol");
  }
}
