package SmartFarm.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CropType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CropType() {
    super(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6aacL, "CropType", "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509356");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_tomato_0 = new EnumerationDescriptor.MemberDescriptor("tomato", "Tomato", 0x4868eb0de61d6aadL, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509357");
  private final EnumerationDescriptor.MemberDescriptor myMember_chilli_0 = new EnumerationDescriptor.MemberDescriptor("chilli", "Chilli", 0x4868eb0de61d6aaeL, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509358");
  private final EnumerationDescriptor.MemberDescriptor myMember_potato_0 = new EnumerationDescriptor.MemberDescriptor("potato", "Potato", 0x4868eb0de61d6ab1L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509361");
  private final EnumerationDescriptor.MemberDescriptor myMember_cabbage_0 = new EnumerationDescriptor.MemberDescriptor("cabbage", "Cabbage", 0x4868eb0de61d6ab5L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509365");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6aacL, 0x4868eb0de61d6aadL, 0x4868eb0de61d6aaeL, 0x4868eb0de61d6ab1L, 0x4868eb0de61d6ab5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_tomato_0, myMember_chilli_0, myMember_potato_0, myMember_cabbage_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "tomato":
        return myMember_tomato_0;
      case "chilli":
        return myMember_chilli_0;
      case "potato":
        return myMember_potato_0;
      case "cabbage":
        return myMember_cabbage_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
