package SmartFarm.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_LightType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LightType() {
    super(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6a93L, "LightType", "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509331");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_UV_0 = new EnumerationDescriptor.MemberDescriptor("UV", "UV light", 0x4868eb0de61d6a94L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509332");
  private final EnumerationDescriptor.MemberDescriptor myMember_blue_0 = new EnumerationDescriptor.MemberDescriptor("blue", "Blue light", 0x4868eb0de61d6a95L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509333");
  private final EnumerationDescriptor.MemberDescriptor myMember_red_0 = new EnumerationDescriptor.MemberDescriptor("red", "Red light", 0x4868eb0de61d6a98L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509336");
  private final EnumerationDescriptor.MemberDescriptor myMember_green_0 = new EnumerationDescriptor.MemberDescriptor("green", "Green light", 0x4868eb0de61d6a9cL, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236509340");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d6a93L, 0x4868eb0de61d6a94L, 0x4868eb0de61d6a95L, 0x4868eb0de61d6a98L, 0x4868eb0de61d6a9cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_UV_0, myMember_blue_0, myMember_red_0, myMember_green_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "UV":
        return myMember_UV_0;
      case "blue":
        return myMember_blue_0;
      case "red":
        return myMember_red_0;
      case "green":
        return myMember_green_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
