package SmartFarm.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AItype extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AItype() {
    super(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d725bL, "AItype", "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236511323");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_sensor_0 = new EnumerationDescriptor.MemberDescriptor("sensor", "Sensor Monitor", 0x4868eb0de61d725cL, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236511324");
  private final EnumerationDescriptor.MemberDescriptor myMember_drone_0 = new EnumerationDescriptor.MemberDescriptor("drone", "Drone Monitor", 0x4868eb0de61d725dL, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236511325");
  private final EnumerationDescriptor.MemberDescriptor myMember_camera_0 = new EnumerationDescriptor.MemberDescriptor("camera", "Camera Monitor", 0x4868eb0de61d7260L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236511328");
  private final EnumerationDescriptor.MemberDescriptor myMember_light_0 = new EnumerationDescriptor.MemberDescriptor("light", "Light Monitor", 0x4868eb0de61d7264L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236511332");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d725bL, 0x4868eb0de61d725cL, 0x4868eb0de61d725dL, 0x4868eb0de61d7260L, 0x4868eb0de61d7264L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_sensor_0, myMember_drone_0, myMember_camera_0, myMember_light_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "sensor":
        return myMember_sensor_0;
      case "drone":
        return myMember_drone_0;
      case "camera":
        return myMember_camera_0;
      case "light":
        return myMember_light_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
