package SmartFarm.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SensorType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SensorType() {
    super(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61c82e3L, "SensorType", "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236450019");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_temp_0 = new EnumerationDescriptor.MemberDescriptor("temp", "Temperature Sensor", 0x4868eb0de61c82e4L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236450020");
  private final EnumerationDescriptor.MemberDescriptor myMember_soil_0 = new EnumerationDescriptor.MemberDescriptor("soil", "Soil monitor", 0x4868eb0de61c82e5L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236450021");
  private final EnumerationDescriptor.MemberDescriptor myMember_water_0 = new EnumerationDescriptor.MemberDescriptor("water", "Water monitor", 0x4868eb0de61c82e8L, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236450024");
  private final EnumerationDescriptor.MemberDescriptor myMember_humid_0 = new EnumerationDescriptor.MemberDescriptor("humid", "Humidity sensor", 0x4868eb0de61c82ecL, "r:3d8221a8-bf28-472f-a550-7226d0477236(SmartFarm.structure)/5217678613236450028");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61c82e3L, 0x4868eb0de61c82e4L, 0x4868eb0de61c82e5L, 0x4868eb0de61c82e8L, 0x4868eb0de61c82ecL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_temp_0, myMember_soil_0, myMember_water_0, myMember_humid_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "temp":
        return myMember_temp_0;
      case "soil":
        return myMember_soil_0;
      case "water":
        return myMember_water_0;
      case "humid":
        return myMember_humid_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
