package SmartFarm.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Farm_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("Farm");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.newLine();
    tgs.append("Total crates");
    tgs.append(" " + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.cratesrequired$tyWJ));
    tgs.newLine();
    tgs.append("No. of Rows: ");
    tgs.append(" " + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.norow$VB$T));
    tgs.append(" Crates in all the column: ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.nocol$VChW));
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.camera$$tV_));
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.drone$$GH$));




  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty cratesrequired$tyWJ = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61ead32L, "cratesrequired");
    /*package*/ static final SProperty norow$VB$T = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61edcfaL, "norow");
    /*package*/ static final SProperty nocol$VChW = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61edcfdL, "nocol");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink camera$$tV_ = MetaAdapterFactory.getContainmentLink(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61d7bbcL, "camera");
    /*package*/ static final SContainmentLink drone$$GH$ = MetaAdapterFactory.getContainmentLink(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4868eb0de61d7269L, 0x4868eb0de61d7bd1L, "drone");
  }
}
