package SmartFarm.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Soil_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("For soil type ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.type$e__d));
    tgs.newLine();
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.ph$eA3f)) {
      tgs.append("Ph sensor");
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$e__d = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904be0L, 0x4ba697e934924cc8L, "type");
    /*package*/ static final SProperty ph$eA3f = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904be0L, 0x4ba697e934924ccaL, "ph");
  }
}
