package SmartFarm.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Water_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.airmoist$i67D)) {
      tgs.append("Humidity Sensor");
      tgs.newLine();

    }
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.soilmoist$i0Ii)) {
      tgs.append("Soil Moisture Sensor");
      tgs.newLine();

    }

  }

  private static final class PROPS {
    /*package*/ static final SProperty airmoist$i67D = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904be1L, 0x4ba697e934924d28L, "airmoist");
    /*package*/ static final SProperty soilmoist$i0Ii = MetaAdapterFactory.getProperty(0x835d7f18a2604c9dL, 0xa7a7f5480713c93dL, 0x4ba697e934904be1L, 0x4ba697e934924d26L, "soilmoist");
  }
}
